version: "3"
services:
  sk-agentry:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .dockervenv:/src/.venv
      - .:/src # 로컬 프로젝트 디렉토리를 컨테이너 '/src'로 마운트
    ports:
      - 8000:8000 # 호스트 머신의 8000번 포트를 Docker의 8000번 포트에 연결
    environment:
      - WATCHFILES_FORCE_POLLING=true # 환경에 따라 핫 리로드를 위해 필요함
      - PATH=/root/.local/bin:/usr/local/bin:$PATH
  db:
    image: mysql:8.0 # 공식 MySQL 이미지 사용 (소문자)
    platform: linux/x86_64 # 애플 실리콘 맥(M1/M2 등)의 경우 필요
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes" # root 계정을 비밀번호 없이 생성
      # MYSQL_ROOT_PASSWORD: 'pass1234'
      # MYSQL_USER: 'demo_user'
      # MYSQL_PASSWORD: 'demo1234'
      MYSQL_DATABASE: "sk-agentry" # demo 데이터베이스를 초기 데이터베이스로 설정
      TZ: "Asia/Seoul" # 시간대를 한국으로 설정
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 33306:3306 # 호스트 머신의 33306번 포트를 Docker의 3306 포트에 연결
volumes:
  mysql_data:
